; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32doit-devkit-v1]
platform = espressif32
board = esp32doit-devkit-v1
framework = arduino

; Sincroniza a velocidade do terminal
monitor_speed = 115200

; Diminui a velocidade de gravação para evitar erros de comunicação no cabo
upload_speed = 115200

; Baixa a biblioteca do leitor RFID
lib_deps = 
    miguelbalboa/MFRC522